# Generated by Django 3.0 on 2019-12-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wain_nro7_app.Trivia')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('xcoordinate', models.FloatField()),
                ('ycoordinate', models.FloatField()),
                ('trivia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Trivia', to='wain_nro7_app.Trivia')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wain_nro7_app.Question')),
            ],
        ),
    ]
