# Generated by Django 3.0 on 2019-12-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wain_nro7_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.DateField()),
                ('gander', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='trivia',
        ),
        migrations.AddField(
            model_name='trivia',
            name='place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Place', to='wain_nro7_app.Place'),
            preserve_default=False,
        ),
    ]
