# Generated by Django 3.0 on 2019-12-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wain_nro7_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
