# Generated by Django 3.0 on 2019-12-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wain_nro7_app', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcoordinate', models.FloatField()),
                ('ycoordinate', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
        migrations.CreateModel(
            name='Difference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate', to='wain_nro7_app.Coordinate')),
            ],
        ),
    ]
