# Generated by Django 3.0 on 2019-12-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wain_nro7_app', '0003_auto_20191224_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difference',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='difference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='wain_nro7_app.Difference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='difference',
            name='place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='difference', to='wain_nro7_app.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trivia',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trivia', to='wain_nro7_app.Place'),
        ),
    ]
