# Generated by Django 3.0 on 2019-12-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wain_nro7_app', '0004_auto_20191224_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='difference',
            name='diffs',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
