# Generated by Django 3.0 on 2019-12-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wain_nro7_app', '0007_auto_20191225_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
